Finished analyses listing
spectre-team/divik-worker pull request #5
Opened 2018-03-22 17:59 UTC by gmrukwa

* separated API and helpers
* helpers grouped by domain
* missing results endpoint added

2018-03-22 18:08 UTC, gmrukwa commented
![](https://github.trello.services/images/mini-trello-icon.png) [DiviK results endpoint is not implemented yet](https://trello.com/c/hxNzNRIZ/423-divik-results-endpoint-is-not-implemented-yet)

2018-03-27 00:19 UTC, mg6 requested changes

2018-03-27 00:19 UTC, mg6 commented on test/discover/test_analysis.py
> +        path for path in paths if path in IS_DIR or path + '/' in IS_DIR
`os.path.sep` needed here.

2018-03-27 06:24 UTC, gmrukwa commented on test/discover/test_analysis.py
> +        path for path in paths if path in IS_DIR or path + '/' in IS_DIR
Accepted.

2018-03-27 23:04 UTC, mg6 submitted a review, later dismissed

2018-03-29 18:28 UTC, Daroslaw submitted a review, later dismissed

2018-04-03 19:14 UTC, mg6 approved these changes
Looks fine; good job.

2018-04-04 15:44 UTC, Daroslaw approved these changes

2018-04-05 11:46 UTC, merged